Feature/SambaNova modelzoo examples
argonne-lcf/user-guides pull request #469
Opened 2024-09-05 15:14 UTC by wcarnold1010

Add a page with runbook-level instructions for running llama 7b text generation and finetuning examples.

2024-09-09 06:35 UTC, felker requested changes

2024-09-09 06:35 UTC, felker commented on docs/ai-testbed/sambanova/example-modelzoo-programs.md
> +Change directory to your modelzoo clone, and set an environment variable to be  host sambanova runts version, then start the container. This example binds a directory containing an openwebtext datase
```suggestion
Change directory to your Model Zoo clone, and set an environment variable to be host SambaNova runts version, then start the container. This example binds a directory containing an OpenWebText dataset. 
```

did you mean to change "runtime" to "runts"?

2024-09-09 18:17 UTC, wcarnold1010 commented on docs/ai-testbed/sambanova/example-modelzoo-programs.md
> +The original python scripts and scripts converted to run on an RDU are also supplied in the modelzoo.<br>
I don't want that section to have extra whitespace, so I used double spaces at the end of the lines instead.

2024-09-10 05:47 UTC, felker requested changes

2024-09-11 17:48 UTC, felker approved these changes

2024-09-11 17:48 UTC, merged