Adding reference to PFS optimization basics
argonne-lcf/user-guides pull request #528
Opened 2024-11-07 00:52 UTC by kaushikvelusamy

2024-11-07 17:46 UTC, felker requested changes
Do not upload PDFs to the repo--- it will bloat the size of `.git/` and the pack, and make development much slower. You should host this https://www.alcf.anl.gov/ (if it isnt already there) and link to it.

2024-11-08 00:39 UTC, kaushikvelusamy commented
FYR, this pdf is not the same pdf under the data mangement section. This is the reduced version of the theory part.

2024-11-08 00:48 UTC, felker commented on docs/aurora/data-management/lustre/flare.md
> +[Follow this link for more information on Lustre Filesystem I/O optimization Basics ](IO-optimization_mcpheeters.pdf)
```suggestion
[Follow this link for more basic information on I/O optimization for the Lustre Filesystem I/O](https://anl.box.com/s/uqmgnkn7i3z22c9xrwef8nn702wl22uy)
```

2024-11-08 00:51 UTC, felker approved these changes

2024-11-08 00:53 UTC, merged