Added profiling docs for Polaris and Aurora
argonne-lcf/user-guides pull request #576
Opened 2024-12-11 23:02 UTC by khossain4337

For Poalris:
- Added nsys and ncu profiling methods

For Aurora
- Added unitrace profiling methods

TODO:
- Add PyTorch Profiler for Polaris
- Add THAPI for Aurora

2025-01-09 00:30 UTC, felker requested changes

2025-01-09 00:30 UTC, felker commented on docs/aurora/data-science/profiling_dl.md
> +### A `unitrace` wrapper
Can you add a title for the script using: https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-a-title

And remove the `###` subsection header

2025-01-09 00:30 UTC, felker commented on docs/aurora/data-science/profiling_dl.md
> +The wrapper above can be deployed using a PBS job script the following way
```suggestion
The wrapper above can be deployed using the following PBS job script:
```

2025-01-09 00:30 UTC, felker commented on docs/polaris/data-science/profiling_dl.md
> +We can use both framework (for example, PyTorch) native profiler and vendor specific
```suggestion
We can use both a framework-specific (for example, PyTorch-specific) native profiler and the vendor-specific NVIDIA
```

2025-01-09 00:30 UTC, felker commented on docs/polaris/data-science/profiling_dl.md
> +[Nsight System User Guide](https://docs.nvidia.com/nsight-systems/UserGuide/index.html)
use unordered list `-`

2025-01-09 00:30 UTC, felker commented on docs/polaris/data-science/profiling_dl.md
> +### An `nsys` wrapper
same comment as before re: code block title

2025-01-09 00:30 UTC, felker commented on docs/polaris/data-science/profiling_dl.md
> +
delete extra newline

2025-01-09 00:30 UTC, felker commented on docs/polaris/data-science/profiling_dl.md
> +Note that, `--env TMPDIR=${TEMPORARY_DIR}` is critical for the `nsys`
```suggestion
Note that `--env TMPDIR=${TEMPORARY_DIR}` is essential for `nsys` to function correctly.
```

2025-01-09 00:30 UTC, felker commented on docs/polaris/data-science/profiling_dl.md
> +functioning.
```suggestion
```

2025-01-09 00:30 UTC, felker commented on docs/polaris/data-science/profiling_dl.md
> +# What's the benchmark work directory?
```suggestion
# What's the working directory for the benchmark?
```

2025-01-09 00:30 UTC, felker commented on docs/polaris/data-science/profiling_dl.md
> +The wrapper above can be deployed using a PBS job script the following way
```suggestion
The wrapper above can be deployed using the following PBS job script:
```

2025-01-09 00:30 UTC, felker commented on docs/polaris/data-science/profiling_dl.md
> +We can get kernel level information (for example roofline, tensorcore usage)
```suggestion
We can get kernel level information (for example roofline, Tensor Core usage)
```

2025-01-09 00:30 UTC, felker commented on docs/polaris/data-science/profiling_dl.md
> +### An `ncu` wrapper
same comment as above re: code block titles

2025-01-09 00:30 UTC, felker commented on docs/polaris/data-science/profiling_dl.md
> +(a gemm kernel in this case).
```suggestion
(a GEMM kernel in this case).
```
or 
```suggestion
(a `gemm` kernel in this case).
```

2025-01-09 00:30 UTC, felker commented on docs/polaris/data-science/profiling_dl.md
> +### For a single rank run
```suggestion
### Single rank run
```

2025-01-09 00:30 UTC, felker commented on docs/polaris/data-science/profiling_dl.md
> +requested wall-time for your batch job.
```suggestion
requested walltime for your batch job.
```

2025-01-09 00:30 UTC, felker commented on docs/polaris/data-science/profiling_dl.md
> +[Nsight System User Guide](https://docs.nvidia.com/nsight-systems/UserGuide/index.html)
Use unordered list to clean up the formatting

2025-01-09 00:30 UTC, felker commented on docs/aurora/data-science/profiling_dl.md
> +There are a few important things to notice in the wrapper.
```suggestion
There are several important shell variables in the wrapper, which may require modification:
```

also change the phrasing on the Polaris profiling doc

2025-01-16 16:20 UTC, khossain4337 commented on docs/aurora/data-science/profiling_dl.md
> +### A `unitrace` wrapper
Done, doing a psuh in a few minutes!

2025-01-16 16:20 UTC, khossain4337 commented on docs/polaris/data-science/profiling_dl.md
> +[Nsight System User Guide](https://docs.nvidia.com/nsight-systems/UserGuide/index.html)
Done, doing a push in a few minutes!

2025-01-16 16:20 UTC, khossain4337 commented on docs/polaris/data-science/profiling_dl.md
> +### An `nsys` wrapper
Done, doing a push in a few minutes!

2025-01-16 17:06 UTC, khossain4337 commented on docs/polaris/data-science/profiling_dl.md
> +
Done! Missed in the earlier pushes, now complete

2025-01-16 17:14 UTC, khossain4337 commented on docs/polaris/data-science/profiling_dl.md
> +### An `ncu` wrapper
Done!

2025-01-16 18:13 UTC, felker requested changes

2025-01-16 18:13 UTC, felker commented on docs/aurora/data-science/profiling_dl.md
> +```bash title="unitrace_wrapper.sh"
```suggestion
```bash linenums="1" title="unitrace_wrapper.sh"
```

2025-01-16 18:13 UTC, felker commented on docs/aurora/data-science/profiling_dl.md
> +for details.
```suggestion
On Aurora we can use the `unitrace` profiler from Intel to profile deep learning applications. Refer to the [`unitrace` documentation page](https://github.com/intel/pti-gpu/tree/master/tools/unitrace)
for details.
```

2025-01-16 18:13 UTC, felker commented on docs/aurora/data-science/profiling_dl.md
> +rank. This profile can be viewed using the [perfetto trace viewer](https://ui.perfetto.dev/)
```suggestion
rank. This profile can be viewed using the [Perfetto trace viewer](https://ui.perfetto.dev/)
```

2025-01-16 18:13 UTC, felker commented on docs/polaris/data-science/profiling_dl.md
> +- [PyTorch Profiler](https://pytorch.org/tutorials/recipes/recipes/profiler_recipe.html)
```suggestion
- [Nsight System User Guide](https://docs.nvidia.com/nsight-systems/UserGuide/index.html)
- [Nsight Compute Documentation](https://docs.nvidia.com/nsight-compute/)
- [Nsight Compute CLI](https://docs.nvidia.com/nsight-compute/NsightComputeCli/index.html)
- [PyTorch Profiler](https://pytorch.org/tutorials/recipes/recipes/profiler_recipe.html)
```

2025-01-16 18:13 UTC, felker commented on docs/polaris/data-science/profiling_dl.md
> +We can use `nsys` to trace an application running on multiple ranks and
duplicate?

2025-01-16 18:13 UTC, felker commented on docs/polaris/data-science/profiling_dl.md
> +summarized through the following command:
```suggestion
Both the `nsys` and `ncu` profiler commands take the following generic structure:
```

2025-01-16 18:13 UTC, felker commented on docs/polaris/data-science/profiling_dl.md
> +
```suggestion
If we want to launch the profiled application with MPI, then `mpiexec` must be used:
```

2025-01-16 18:13 UTC, felker commented on docs/polaris/data-science/profiling_dl.md
> +We can use `nsys` to trace an application running on multiple ranks and
previous paragraph says 2 nodes, this one says 4 nodes

2025-01-16 18:13 UTC, felker commented on docs/polaris/data-science/profiling_dl.md
> +```bash title="pbs_jobscript_nsys.sh"
```suggestion
```bash linenums="1" title="pbs_jobscript_nsys.sh"
```

2025-01-16 18:13 UTC, felker commented on docs/polaris/data-science/profiling_dl.md
> +```bash title="ncu_wrapper.sh"
```suggestion
```bash linenums="1" title="ncu_wrapper.sh"
```

2025-01-16 18:13 UTC, felker commented on docs/polaris/data-science/profiling_dl.md
> +- [Nsight Compute CLI](https://docs.nvidia.com/nsight-compute/NsightComputeCli/index.html)
```suggestion
- [Nsight System User Guide](https://docs.nvidia.com/nsight-systems/UserGuide/index.html)
- [Nsight Compute Documentation](https://docs.nvidia.com/nsight-compute/)
- [Nsight Compute CLI](https://docs.nvidia.com/nsight-compute/NsightComputeCli/index.html)
```

2025-01-16 18:13 UTC, felker commented on docs/polaris/data-science/profiling_dl.md
> +```py title="pytorch_profiler_example.py"
```suggestion
```python linenums="1" title="pytorch_profiler_example.py"
```

2025-01-16 18:13 UTC, felker commented on mkdocs.yml
> +  - Aurora:
something isnt correct with your mege commit. The change should be 1-2 lines. Did you change the whitespace indentation?

2025-01-16 18:57 UTC, khossain4337 commented on mkdocs.yml
> +  - Aurora:
I messed something up for sure! For now, I have replaced the `mkdocs.yml` on my branch with the `mkdocs.yml` from the main branch. For the page does not show up in the nav bar on the side... Initial issues started with trying to fix that couple of weeks ago

In the next push I will just leave this out of the nav bar, do you think that is okay?

2025-01-16 19:02 UTC, khossain4337 commented on docs/polaris/data-science/profiling_dl.md
> +We can use `nsys` to trace an application running on multiple ranks and
Yes! Fixed now!

2025-01-16 19:22 UTC, khossain4337 commented on mkdocs.yml
> +  - Aurora:
I tried my best!

```
(test_docs_server) khalidhossain@MacBook-Pro-39 user-guides % git diff main kh_dlprof mkdocs.yml 
diff --git a/mkdocs.yml b/mkdocs.yml
index eb58cfb1..299c64e0 100644
--- a/mkdocs.yml
+++ b/mkdocs.yml
@@ -77,6 +77,7 @@ nav:
         #- Applications:
           #- gpt-neox: aurora/data-science/applications/gpt-neox.md
         - Containers: aurora/data-science/containers/containers.md
+        - Profiling: aurora/data-science/profiling_dl.md
         - Frameworks:
           - DeepSpeed: aurora/data-science/frameworks/deepspeed.md
           #- JAX: aurora/data-science/frameworks/jax.md
@@ -153,6 +154,7 @@ nav:
     - Data Science:
         - Julia: polaris/data-science/julia.md
         - Python: polaris/data-science/python.md
+        - Profiling: polaris/data-science/profiling_dl.md
         - Frameworks:
             - TensorFlow: polaris/data-science/frameworks/tensorflow.md
             - PyTorch: polaris/data-science/frameworks/pytorch.md
```

Hope this will work!

2025-01-16 19:34 UTC, merged