Added Aurora DeepSpeed content
argonne-lcf/user-guides pull request #581
Opened 2024-12-16 18:20 UTC by hatanp

First draft for DeepSpeed on Aurora. Modified from Polaris instructions and tested to work.

2025-01-06 17:53 UTC, felker requested changes

2025-01-06 17:53 UTC, felker commented on docs/aurora/data-science/frameworks/deepspeed.md
> +        2. Create a `#!bash .deepspeed_env` containing the environment
I had a conversation with @saforem2 about the use of syntax highlighting for inline code markup like you use here with `#!bash ...` 

We concluded that it isnt really worth the marginal gains for such short pieces of text, since it doesnt render in GitHub Flavored Markdown and has different escaping conventions. 
![image](https://github.com/user-attachments/assets/5027e437-b957-42d7-89c0-b50e608c022e)

Kinda degrades the readability when you are editing someone else's source text. Have you found it to be helpful?

2025-01-09 20:26 UTC, hatanp commented on docs/aurora/data-science/frameworks/deepspeed.md
> +        2. Create a `#!bash .deepspeed_env` containing the environment
Unfortunately I am not following. This was just copied from Polaris docs and I did no changes to the formatting nor am I familiar with it. This looked fine and just like the Polaris docs when I rendered the document. Is the issue that this is hard to read in GitHub? What was the solution you concluded on in the discussion? 

I have no opinion on how syntax highlighting should be implemented so feel free to propose changes as seems like both of you have better idea than I do. I do not have the skills to make educated choices on this. I just took something that was used before and worked in the rendered document.

2025-01-09 20:29 UTC, hatanp commented on docs/aurora/data-science/frameworks/deepspeed.md
> +for using / cloning the base environment can be found [here](../python.md).
To me "using and cloning" seems to imply the two are related. They are two separate topics. The slash was how it is in Polaris documentation. If words are preferred, then I would maybe go with "or"

2025-01-09 20:30 UTC, felker commented on docs/aurora/data-science/frameworks/deepspeed.md
> +        2. Create a `#!bash .deepspeed_env` containing the environment
I am suggesting just using `.deepspeed_env`

2025-01-09 20:31 UTC, felker commented on docs/aurora/data-science/frameworks/deepspeed.md
> +        2. Create a `#!bash .deepspeed_env` containing the environment
```
`.deepspeed_env`
instead of
`#!bash .deepspeed_env`
````

2025-01-09 20:34 UTC, felker commented on docs/aurora/data-science/frameworks/deepspeed.md
> +for using / cloning the base environment can be found [here](../python.md).
no need to overthink this one; go with whatever you find best. 

instructions for both steps are found at that link, hence why I suggested "and"

IMO using "or" or "and" seems a bit more polished than "/" in our user docs, although I am guilty of using it from time to time

2025-01-09 20:35 UTC, hatanp commented
@saforem2 Did you have a chance to check this document? I just took whatever was in Polaris docs and modified it a bit so some details could have escaped me, so a second pair of eyes on this would be great. Also, looks like I did not receive any notifications from all the comments here and I now resolved a few. Thanks @felker!

2025-01-10 18:06 UTC, felker commented on docs/aurora/data-science/frameworks/deepspeed.md
> +        2. Create a `#!bash .deepspeed_env` containing the environment
https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#highlighting-inline-code-blocks 
this where the feature is discussed--- still can be useful for highlighting syntax for inline Python etc. but less useful for a single word Bash command or filename

2025-01-13 16:50 UTC, Eugene29 commented
I was able to follow the documentation with ease and was able to run with either deepspeed and mpiexec. I think it is already in good shape, but I left comments where I think possible improvements can be made!

2025-01-14 21:11 UTC, FilippoSimini commented on docs/aurora/data-science/frameworks/deepspeed.md
> +    execution](../../../running-jobs/job-and-queue-scheduling.md) for
For Aurora, this path should be `../../../running-jobs-aurora.md` instead of `../../../running-jobs/job-and-queue-scheduling.md`.
Ideally, all systems should have the same directory structure, if possible, to avoid these inconsistencies in relative paths.

2025-01-15 06:24 UTC, saforem2 commented on docs/aurora/data-science/frameworks/deepspeed.md
> +for using / cloning the base environment can be found [here](../python.md).
yeah I think any of the above are OK especially for a first draft

a possible alternative could maybe be:

> Further instructions for working with the base environment can be found [here](../python.md)

or something similar :shrug:

2025-01-15 21:03 UTC, hatanp commented on docs/aurora/data-science/frameworks/deepspeed.md
> +    execution](../../../running-jobs/job-and-queue-scheduling.md) for
Thanks for spotting this one! Actually it is `../../running-jobs-aurora.md`

2025-01-15 21:37 UTC, hatanp commented on docs/aurora/data-science/frameworks/deepspeed.md
> +for using / cloning the base environment can be found [here](../python.md).
Updated according to suggestion from @saforem2. Thanks!

2025-01-15 21:40 UTC, hatanp commented
I have implemented all the suggestions. Now looks like merge is blocked by requested changes by @felker. Could you check this out and approve or request further changes?

2025-01-15 21:42 UTC, hatanp commented on docs/aurora/data-science/frameworks/deepspeed.md
> +        2. Create a `#!bash .deepspeed_env` containing the environment
Removed the small pieces of extra notation. I do not know how to link that here.

2025-01-16 05:37 UTC, felker commented on docs/aurora/data-science/frameworks/deepspeed.md
> +[here](https://github.com/argonne-lcf/GettingStarted/tree/master/DataScience/DeepSpeed).
is this comment still accurate, or can it be removed now?

2025-01-16 16:46 UTC, merged