add PyTorch Geometric (PyG) on Aurora
argonne-lcf/user-guides pull request #582
Opened 2024-12-16 21:45 UTC by FilippoSimini

2025-01-06 17:53 UTC, felker requested changes

2025-01-06 17:53 UTC, felker commented on docs/aurora/data-science/frameworks/pyg.md
> +  #### `gcn.py`
better to use code block titles instead of section heads

https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-a-title

2025-01-08 08:35 UTC, felker commented on docs/polaris/applications-and-libraries/applications/namd.md
> +``` bash
```suggestion
```bash
```

2025-01-08 08:35 UTC, felker commented on docs/polaris/applications-and-libraries/applications/amber.md
> +1. Download AmberTools24 and Amber24 from Amber [website](https://ambermd.org/GetAmber.php). Note, they are two separate downloads. Copy the tarballs `AmberTools24.tar.bz2` and `Amber24.tar.bz2` into
```suggestion
1. Download AmberTools24 and Amber24 from Amber [website](https://ambermd.org/GetAmber.php). Note, they are two separate downloads. Copy the tarballs `AmberTools24.tar.bz2` and `Amber24.tar.bz2` into a home or project directory (e.g. `$HOME/Amber/`).
```

2025-01-08 08:36 UTC, felker commented on docs/aurora/data-science/python.md
> +> [!IMPORTANT]
I didnt check the rendering--- does this conform to https://squidfunk.github.io/mkdocs-material/reference/admonitions/ ?

2025-01-08 08:37 UTC, felker commented
was there a mistaken merge? seems like the original branch got mixed with unrelated edits to Cerebras and Polaris pages...

2025-01-08 13:52 UTC, FilippoSimini commented
yes, it's all mixed up. let me delete this branch and open a new one.

2025-01-08 13:52 UTC, closed without merging