Gpytorch
argonne-lcf/user-guides pull request #586
Opened 2024-12-18 22:08 UTC by mngom2

Gpytorch docs on Polaris and Aurora

2024-12-19 16:13 UTC, felker commented on docs/aurora/data-science/frameworks/gpytorch.md
> +i# Guide of Login to Aurora Load Environments, Run Jobs, and Install GPytorch
```suggestion
# Guide of Login to Aurora Load Environments, Run Jobs, and Install GPytorch
```

2025-01-14 21:14 UTC, felker requested changes

2025-01-14 21:14 UTC, felker commented on docs/aurora/data-science/frameworks/gpytorch.md
> +Create a 'activation_env.sh' file that contains
```suggestion
Create a `activation_env.sh` file that contains the following lines:
```

2025-01-14 21:14 UTC, felker commented on docs/aurora/data-science/frameworks/gpytorch.md
> +```
```suggestion
```bash title="activation_env.sh"
```

2025-01-14 21:14 UTC, felker commented on docs/aurora/data-science/frameworks/gpytorch.md
> +set the device as follows in the code:
```suggestion
and set the device as follows in the code:
```

2025-01-14 21:14 UTC, felker commented on docs/aurora/data-science/frameworks/gpytorch.md
> +```
```suggestion
```python
```

2025-01-14 21:14 UTC, felker commented on docs/polaris/data-science/frameworks/gpytorch.md
> +* -A for project name
or actually, delete this whole section since it is redundant with the pages on job submissionn. I woudl suggested replacing it with something similar to what is used at the top of 
https://docs.alcf.anl.gov/polaris/data-science/frameworks/deepspeed/

```
!!! note

    The instructions below should be **ran directly from a compute node**.

    Explicitly, to request an interactive job (from `polaris-login`):
    ```bash
    qsub -A <project> -q debug-scaling -l select=2 -l walltime=01:00:00 -I
    ```

    Refer to [job scheduling and
    execution](../../../running-jobs/job-and-queue-scheduling.md) for
    additional information.
```

2025-01-14 21:14 UTC, felker commented on docs/polaris/data-science/frameworks/gpytorch.md
> +Load the Conda Environment (Module) with Pytorch, since our GPytorch has Pytorch dependency
```suggestion
Load the Anaconda environment module, which contains a PyTorch installation, since GPyTorch has PyTorch as a dependency:
```

2025-01-14 21:14 UTC, felker commented on docs/polaris/data-science/frameworks/gpytorch.md
> +#### 2. Once on a Compute Node, Load Modules
```suggestion
#### 2. Load modules
```

2025-01-14 21:14 UTC, felker commented on docs/polaris/data-science/frameworks/gpytorch.md
> +#### 1. Login and queue a job
Why do you go from # section heading to #### ?

2025-01-14 21:14 UTC, felker commented on docs/polaris/data-science/frameworks/gpytorch.md
> +### After the First Time
```suggestion
### Loading environment in future sessions
```

2025-01-14 21:14 UTC, felker commented on docs/polaris/data-science/frameworks/gpytorch.md
> +## Using Jupyter Notebook to Run GPytorch on Polaris
```suggestion
## Using Jupyter Notebook to run GPyTorch on Polaris
```

2025-01-14 21:14 UTC, felker commented on docs/polaris/data-science/frameworks/gpytorch.md
> +### Approach 1 - Use Jupyter Hub
```suggestion
### Approach 1 - Use ALCF JupyterHub
```

and fix formatting below similarly

2025-01-14 21:14 UTC, felker commented on docs/polaris/data-science/frameworks/gpytorch.md
> +Note: depending on the system and environment, you might need to install the "ipykernel" package first. The python_venv that I just created has the ipykernel module.
```suggestion
Note: depending on the system and environment, you might need to install the "ipykernel" package first. The `python_venv` that I just created has the `ipykernel` module.
```

2025-01-14 21:14 UTC, felker commented on docs/polaris/data-science/frameworks/gpytorch.md
> +Go back to your .ipynb file, change kernel to python_venv from the dropdown menu, and we'll be good to run GPytorch!
```suggestion
Go back to your `.ipynb` file, change kernel to `python_venv` from the dropdown menu, and we'll be good to run GPyTorch!
```

2025-01-14 21:14 UTC, felker commented on docs/polaris/data-science/frameworks/gpytorch.md
> +Go back to your .ipynb file, change kernel to python_venv from the dropdown menu, and we'll be good to run GPytorch!
similarly below

2025-01-15 19:18 UTC, closed without merging

2025-01-15 19:34 UTC, mngom2 commented on docs/polaris/data-science/frameworks/gpytorch.md
> +#### 1. Login and queue a job
The first one is the doc title and the second a section. If it is weird, I can change it.

2025-01-16 05:40 UTC, felker commented on docs/polaris/data-science/frameworks/gpytorch.md
> +#### 1. Login and queue a job
Yes, I understand that, but why not use `##` for the section instead of `####`? I see the same issue in the new PR #635